name: build-windows-exe

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniforge (Conda)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          channels: conda-forge
          channel-priority: strict
          conda-remove-defaults: true
          environment-file: environment.yml     # <-- create from your file
          activate-environment: estimator-build # <-- and activate it
          use-mamba: true
          auto-activate-base: false

      - name: Create environment
        shell: bash -l {0}
        run: |
          mamba env update -n estimator-build -f environment.yml
          conda activate estimator-build
          python -V

      - name: Build EXE with PyInstaller
        shell: bash -l {0}
        run: |
          # Build a tiny launcher so we import the package correctly.
          cat > run_estimator.py <<'PY'
          from estimator529 import main
          if __name__ == '__main__':
              import multiprocessing
              multiprocessing.freeze_support()
              main()
          PY

          pyinstaller --onefile --windowed \
            --name 529Estimator \
            --collect-all matplotlib \
            --hidden-import tkinter.filedialog \
            --hidden-import tkinter.colorchooser \
            --hidden-import tkinter.messagebox \
            --hidden-import tkinter.scrolledtext \
            -p src run_estimator.py

          ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 529Estimator-windows
          path: dist/529Estimator.exe

  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: 529Estimator-windows
          path: .

      - name: Publish GitHub Release asset
        uses: softprops/action-gh-release@v2
        with:
          files: 529Estimator.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
