name: build-windows-exe

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash -l {0}   # <<< critical: load conda init

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniforge (Conda)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          channels: conda-forge
          channel-priority: strict
          conda-remove-defaults: true
          environment-file: environment.yml
          activate-environment: estimator-build
          use-mamba: true
          auto-activate-base: false

      - name: Sanity (no activation)
        shell: bash
        run: |
          "$CONDA/condabin/conda.bat" run -n estimator-build python -V
          "$CONDA/condabin/conda.bat" run -n estimator-build python -c "import tkinter, matplotlib; print('deps OK')"
          "$CONDA/condabin/conda.bat" run -n estimator-build pyinstaller --version

      - name: Build EXE (no activation)
        shell: bash
        run: |
          cat > run_estimator.py <<'PY'
          from estimator529 import main
          if __name__ == '__main__':
              import multiprocessing
              multiprocessing.freeze_support()
              main()
          PY

          "$CONDA/condabin/conda.bat" run -n estimator-build pyinstaller --onefile --windowed \
            --name 529Estimator \
            --collect-all matplotlib \
            --hidden-import tkinter.filedialog \
            --hidden-import tkinter.colorchooser \
            --hidden-import tkinter.messagebox \
            --hidden-import tkinter.scrolledtext \
            -p src run_estimator.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 529Estimator-windows
          path: dist/529Estimator.exe
  release:
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write  # required for creating a release
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Publish GitHub Release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            529Estimator.exe
            529Estimator-windows.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}